name: EC2 provisioning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  
  AWS_REGION : "ap-southeast-1"
    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-region: ap-southeast-1
           role-to-assume: arn:aws:iam::375649924539:role/GithubActionRole
           role-session-name: GithubActionRole
           
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
      
      - name: Terraform init, plan and apply
        run: |
           terraform init
           
      - name: Terraform plan
        run: |
           terraform plan
        working-directory: ../
        
      - name: Terraform apply
        run: |
            terraform apply
        working-directory: ../
