name: EC2 provisioning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-region: ap-southeast-1
           role-to-assume: arn:aws:iam::375649924539:role/GithubActionRole
           
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2
      
      - name: Terraform init, plan and apply
        run: |
           terraform init
           
      - name: Terraform plan
        run: |
           terraform plan
        working-directory: ../
        
      - name: Terraform apply
        run: |
            terraform apply
        working-directory: ../
